### ISSUE TITLE
swap bg doesnt work with spacemacs

### ISSUE THREAD

**Issue by vn-ki** [hlissner/emacs-solaire-mode#25]
I think this is related to #7 but I don't know enough elisp to do this on my own. I would really appreciate your help

**Comment by hlissner** [comment]
I'm afraid I don't use Spacemacs, and since my psychic abilities aren't what they used to be, I'll need a _little_ more help figuring out what "it doesn't work" means.

What code have you tried? What theme are you using it with? Where in the load process did you use `solaire-mode-swap-bg`? Did you use it before the theme loads or after the theme loads? Were any errors or warnings logged to the \*Messages\* buffer when it's called? Can what you tried be linked to, screenshot or screencast?

If you copy paste this into your spacemacs config, does it not work?

```elisp
(use-package solaire-mode
  :hook
  ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  (minibuffer-setup . solaire-mode-in-minibuffer)
  :config
  (solaire-global-mode +1)
  (solaire-mode-swap-bg))
```

**Comment by vn-ki** [comment]
What code have you tried?

I tried the above code.

What theme are you using it with?

Tried both onedark and Iosevka

Where in the load process did you use solaire-mode-swap-bg? Did you use it before the theme loads or after the theme loads? 

Before the theme is loaded, I believe.

Were any errors or warnings logged to the *Messages* buffer when it's called? 

No

Thanks for your helping mentality but I fixed and I don't know how (which is the worst kind of fix there is).

Hopefully it stays fixed.

**Comment by hlissner** [comment]
> Before the theme is loaded, I believe.

I imagine this is the problem. `solaire-mode-swap-bg` must be used after the theme is loaded.

> Thanks for your helping mentality but I fixed and I don't know how (which is the worst kind of fix there is).

Happy to help! I'm glad you figured it out.
