### ISSUE TITLE
Solaire mode swap bg has no effect

### ISSUE THREAD

**Issue by jwintz** [hlissner/emacs-solaire-mode#7]
Hi, 

Finally switched to a doom private layer. I have a `+ui.el` that is loaded by `config.el` and sets `doom-nord` as the `doom-theme`, and tries to setup solaire mode the following way:

```
(setq doom-theme 'doom-nord)

(after! doom-themes
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config)
  (doom-themes-org-config))

(after! solaire-mode
  (solaire-mode-swap-bg))
```

However, the background is not swapped.

**Comment by hlissner** [comment]
This is a `doom` issue. You need to attach `solaire-mode-swap-bg` to `doom-init-theme-hook`, so that it runs after the theme has been loaded.

In fact, those `doom-themes-*-config` should be attached to `doom-init-theme-hook` as well.

By the way, all this is already present in the `:ui doom` module. Is there a reason you are not using it? If you did, you'd only need:

```elisp
;; in your private config.el
(setq doom-theme 'doom-nord)
(add-hook 'doom-init-theme-hook #'solaire-modeswap-bg t)
```

**Comment by jwintz** [comment]
Fixed by https://github.com/hlissner/emacs-doom-themes/pull/148.
